# Generated by Django 2.2.16 on 2022-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220601_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'Administrator'), ('m', 'Moderator'), ('u', 'User')], default='u', max_length=1),
        ),
    ]
