# Generated by Django 2.2.16 on 2022-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220605_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
