# Generated by Django 2.2.16 on 2022-06-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='username',
            new_name='user',
        ),
    ]
