# Generated by Django 2.2.16 on 2022-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220604_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('m', 'moderator'), ('u', 'user')], default='u', max_length=1),
        ),
    ]
