# Generated by Django 2.2.16 on 2022-06-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220608_0118'),
        ('reviews', '0002_auto_20220606_0128'),
    ]

    operations = [
    ]
