# Generated by Django 2.2.16 on 2022-06-13 13:59

import celery.local
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_auto_20220613_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(celery.local.Proxy.__getitem__)], verbose_name='Год выхода'),
        ),
    ]
